=== MBVTracks/XML/XSD/Museos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="museos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="museo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string"></xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ciudad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string"></xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="pais">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string"></xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MBVTracks/XML/Museos.xml
<?xml version="1.0" encoding="UTF-8"?>
<museos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="XSD/Museos.xsd">
  <museo>
    <nombre>Museo del Prado</nombre>
    <ciudad>Madrid</ciudad>
    <pais>Espa√±a</pais>
  </museo>
  <museo>
    <nombre>British Museum</nombre>
    <ciudad>Londres</ciudad>
    <pais>Reino Unido</pais>
  </museo>
  <museo>
    <nombre>National Gallery</nombre>
    <ciudad>Londres</ciudad>
    <pais>Reino Unido</pais>
  </museo>
</museos>
